# cicd_2_gcp_k8s.yml
name: ci-cd to k8s

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "k8s" ]
  pull_request:
    branches: [ "k8s" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  REPO: backstage-from-scatch-demo
  IMAGE: backstage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: yarn install

      - name: Compile TypeScript
        run: yarn tsc

      - name: Run Unit Tests
        run: yarn test:all

      - name: Build the application
        run: yarn build:all

      - name: Ensure Build Artifacts are Present
        run: |
          ls packages/backend/dist/
          echo "Artifacts: skeleton.tar.gz and bundle.tar.gz should be present"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: yarn install

      - name: Build the application
        run: yarn build:all

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GKE_REGION }}-docker.pkg.dev

      - name: Create Artifact Registry Repository if it doesn't exist
        run: |
          gcloud artifacts repositories describe $REPO \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --location=${{ secrets.GKE_REGION }} || \
          gcloud artifacts repositories create $REPO \
            --repository-format=docker \
            --location=${{ secrets.GKE_REGION }} \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Build image
        run: |
          ls packages/backend/dist/
          echo "Building Docker image..."
          docker build --no-cache \
            -t ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO/$IMAGE:$GITHUB_SHA \
            -f packages/backend/Dockerfile .

      - name: Push image to Artifact Registry
        run: |
          docker push ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO/$IMAGE:$GITHUB_SHA

      - name: Get GKE Cluster credentials
        run: |
          gcloud container clusters get-credentials \
            ${{ secrets.GKE_CLUSTER }} \
            --region ${{ secrets.GKE_REGION }}

      - name: Deploy to Kubernetes
        run: |
          echo "Deploying to Kubernetes..."

          kubectl apply -f k8s/

          kubectl set image deployment/backstage \
            backstage=${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO/$IMAGE:$GITHUB_SHA \
            -n backstage

          echo "kubectl get pods -n backstage..."
          kubectl get pods -n backstage

          echo "kubectl describe pod -n backstage..."
          kubectl describe pod -n backstage
